[package]
name = "spark_messages"
version = "0.1.0"
edition = "2024"

[dependencies]
async-button = "0.2.0"
serde = { version = "1", default-features = false, features = ["derive"] }

# TODO: in the future, use this crate to handle new message types/protocl changes
#serde-versioning = "1.0.219"